import Head from 'next/head'
import Footer from '../Components/Footer/Footer';
import Gallery from '../Components/Gallery/Gallery';
import Header from '../Components/Header/Header';



export default function Home() {
  return (
    <div className='duration-500'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-black'>
        <Header />
        <Gallery />
        <Footer />
      </main>
    </div>
  )
}
