import Head from 'next/head'
import Banner from '../Components/Header/Banner/Banner';
import Navbar from '../Components/Header/Navbar/Navbar';



export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Banner />
      
    </div>
  )
}
